---
title: "Checking Out Data"
author: "Theo"
date: "10/16/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# seeing whats up with our data and how big it is, also if its any good

```{r}
library(readr)
```


#changing names and deleting belgium-luxembourg 
```{r}

afgan_cambo <- read_csv("RAW_CSV_DATA/afgan-cambo.csv")

afgan_cambo$Area[afgan_cambo$Area == "Bolivia (Plurinational State of)"] <- "Bolivia"

afgan_cambo$Area[afgan_cambo$Area == "Brunei Darussalam"] <- "Brunei"
 
afgan_cambo$Area[afgan_cambo$Area == "Cabo Verde"] <- "Cape Verde"

afgan_cambo <- afgan_cambo[afgan_cambo$Area != "Belgium-Luxembourg", ]

afgan_cambo <- read.csv("RAW_CSV_DATA/afgan-cambo.csv")

write.csv(afgan_cambo, file = "fully_afgan_cambo_cleaned.csv")

```


```{r}

Tanz_Zimb <- read_csv("RAW_CSV_DATA/Tanz-Zimb.csv")

Tanz_Zimb$Area[Tanz_Zimb$Area == "United Republic of Tanzania"] <- "Tanzania"

Tanz_Zimb$Area[Tanz_Zimb$Area == "Venezuela (Bolivarian Republic of)"] <- "Venezuela"

Tanz_Zimb$Area[Tanz_Zimb$Area == "Viet Nam"] <- "Vietnam"

Tanz_Zimb <- Tanz_Zimb[Tanz_Zimb$Area != "Yugoslav SFR", ]

Tanz_Zimb <- read.csv("RAW_CSV_DATA/Tanz-Zimb.csv")

write.csv(Tanz_Zimb, file = "fully_tanz_zimb_cleaned.csv")

```

#changed Tanz_Zimb names (Vietnam, Tanzania, Venezuela)
